# Generated by Django 4.2.6 on 2023-10-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0002_alter_photo_options_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Марка і модель')),
                ('year', models.IntegerField(max_length=4, verbose_name='Рік')),
                ('image', models.ManyToManyField(blank=True, to='usdp.photo', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
    ]
