# Generated by Django 4.2.6 on 2023-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0003_ourcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcar',
            name='year',
            field=models.IntegerField(verbose_name='Рік'),
        ),
    ]
