# Generated by Django 4.2.6 on 2023-10-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0004_alter_ourcar_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcar',
            name='auction_price',
            field=models.IntegerField(default=0, verbose_name='Ціна аукціону'),
        ),
        migrations.AddField(
            model_name='ourcar',
            name='final_price',
            field=models.IntegerField(default=0, verbose_name='Фінальна ціна'),
        ),
    ]
