# Generated by Django 4.2.6 on 2023-10-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0005_ourcar_auction_price_ourcar_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcar',
            name='url',
            field=models.CharField(default='https://www.copart.com', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='ourcar',
            name='auction_price',
            field=models.CharField(default='0', max_length=15, verbose_name='Ціна аукціону'),
        ),
        migrations.AlterField(
            model_name='ourcar',
            name='final_price',
            field=models.CharField(default='0', max_length=15, verbose_name='Фінальна ціна'),
        ),
    ]
