# Generated by Django 4.2.6 on 2023-10-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0006_ourcar_url_alter_ourcar_auction_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/logo')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотипи',
            },
        ),
    ]
