# Generated by Django 4.2.6 on 2023-10-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0007_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30, verbose_name='Марка')),
                ('model', models.CharField(max_length=15, verbose_name='Модель')),
                ('price', models.CharField(default='3000$', max_length=50, verbose_name='Ціна')),
                ('phone', models.CharField(default='+380935555555', max_length=15, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Вспливаюча форма',
                'verbose_name_plural': 'Вспливаючі форми',
            },
        ),
    ]
