# Generated by Django 4.2.6 on 2023-10-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0009_make_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='make',
            options={'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Моделі'},
        ),
    ]
