# Generated by Django 4.2.6 on 2023-10-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0010_alter_make_options_alter_model_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modals',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usdp.make'),
        ),
        migrations.AlterField(
            model_name='modals',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usdp.model'),
        ),
    ]
