# Generated by Django 4.2.6 on 2023-10-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0011_alter_modals_make_alter_modals_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=5000, verbose_name='Ціна лота')),
            ],
            options={
                'verbose_name': 'Ціна лота',
                'verbose_name_plural': 'Ціни лотів',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=30, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типи',
            },
        ),
        migrations.RemoveField(
            model_name='model',
            name='make',
        ),
        migrations.RemoveField(
            model_name='modals',
            name='make',
        ),
        migrations.RemoveField(
            model_name='modals',
            name='model',
        ),
        migrations.DeleteModel(
            name='Make',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AddField(
            model_name='modals',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usdp.type'),
        ),
        migrations.AlterField(
            model_name='modals',
            name='price',
            field=models.ForeignKey(default=5000, on_delete=django.db.models.deletion.CASCADE, to='usdp.price'),
        ),
    ]
