# Generated by Django 4.2.6 on 2023-10-23 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0012_price_type_remove_model_make_remove_modals_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modals',
            name='price',
            field=models.ForeignKey(default='5000$', on_delete=django.db.models.deletion.CASCADE, to='usdp.price'),
        ),
        migrations.AlterField(
            model_name='modals',
            name='type',
            field=models.ForeignKey(default='Седан', on_delete=django.db.models.deletion.CASCADE, to='usdp.type'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Ціна лота'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Тип'),
        ),
    ]
