# Generated by Django 4.2.6 on 2023-10-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0013_alter_modals_price_alter_modals_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Місце продажу')),
            ],
            options={
                'verbose_name': 'Місце продажу',
                'verbose_name_plural': 'Місця продажу',
            },
        ),
    ]
