# Generated by Django 4.2.6 on 2023-10-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0014_salelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelocation',
            name='shipping_USA',
            field=models.IntegerField(default=225, verbose_name='Доставка по США'),
        ),
        migrations.AddField(
            model_name='salelocation',
            name='shipping_ocean',
            field=models.IntegerField(default=1000, verbose_name='Доставка по США'),
        ),
    ]
