# Generated by Django 4.2.6 on 2023-10-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0015_salelocation_shipping_usa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLocationIAAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Місце продажу')),
                ('shipping_USA', models.IntegerField(default=225, verbose_name='Доставка по США')),
                ('shipping_ocean', models.IntegerField(default=1000, verbose_name='Доставка по США')),
            ],
            options={
                'verbose_name': 'Місце продажу IAAI',
                'verbose_name_plural': 'Місця продажу IAAI',
            },
        ),
        migrations.RenameModel(
            old_name='SaleLocation',
            new_name='SaleLocationCopard',
        ),
        migrations.AlterModelOptions(
            name='salelocationcopard',
            options={'verbose_name': 'Місце продажу Copard', 'verbose_name_plural': 'Місця продажу Copard'},
        ),
    ]
