# Generated by Django 4.2.6 on 2023-10-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0016_salelocationiaai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Бюджет авто', 'verbose_name_plural': 'Бюджети авто'},
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Бюджет авто'),
        ),
    ]
