# Generated by Django 4.2.6 on 2023-10-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0017_alter_price_options_alter_price_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modals',
            name='phone',
            field=models.CharField(default='+380', max_length=15, verbose_name='Телефон'),
        ),
    ]
