# Generated by Django 4.2.6 on 2023-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdp', '0018_alter_modals_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AddField(
            model_name='ourcar',
            name='drive',
            field=models.CharField(default='All Wheel Drive', max_length=30, verbose_name='Привід'),
        ),
        migrations.AddField(
            model_name='ourcar',
            name='engine',
            field=models.CharField(default='0', max_length=15, verbose_name='Двигун'),
        ),
        migrations.AddField(
            model_name='ourcar',
            name='fuel',
            field=models.CharField(default='Бензин', max_length=15, verbose_name='Паливо'),
        ),
        migrations.AddField(
            model_name='ourcar',
            name='main_damage',
            field=models.CharField(default='Front End', max_length=15, verbose_name='Основне ушкодження'),
        ),
        migrations.AddField(
            model_name='ourcar',
            name='mileage',
            field=models.CharField(default='100000', max_length=15, verbose_name='Пробіг'),
        ),
        migrations.AddField(
            model_name='ourcar',
            name='secondary_damage',
            field=models.CharField(default='Minor Dent/Scratches', max_length=50, verbose_name='Другорядне ушкодження'),
        ),
    ]
